package dev.jdata.db.engine.server.network.protocol;

public enum ProtocolMessageType {

    SETUP,
    EXECUTE_SQL,
    PREPARE_STATEMENT,
    EXECUTE_PREPARED_STATEMENT,
    EXECUTE_PREPARED_STATEMENT_PARAMETERS,
    EXECUTE_PREPARED_STATEMENT_PARAMETER_ROW_START,
    EXECUTE_PREPARED_STATEMENT_PARAMETER_ROW_LARGE_OBJECT,
    EXECUTE_PREPARED_STATEMENT_PARAMETER_ROW_COMPLETION,
    EXECUTE_PREPARED_STATEMENT_COMPLETION,
    ADD_PREPARED_STATEMENT_BATCH,
    EXECUTE_PREPARED_STATEMENT_BATCH,
    FREE_PREPARED_STATEMENT;


    public static ProtocolMessageType fromByte(byte value) {

        throw new UnsupportedOperationException();
    }
}
